/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "server/templates/**/*.html",
    "server/static/js/**/*.js",
  ],
  darkMode: ['variant', '[data-color-scheme="dark"] &'],
  safelist: [
    'bg-kawaii-primary/20',
    'bg-kawaii-primary/10',
    'bg-kawaii-primary/30',
    'dark:bg-kawaii-primary/30',
    'bg-kawaii-danger/10',
    'dark:bg-kawaii-danger/15',
    'border-kawaii-danger/30',
    'dark:border-kawaii-danger/40',
    'bg-kawaii-success/15',
    'border-kawaii-success/30',
    'border-kawaii-primary/30',
    'border-kawaii-line/50',
    'hover:bg-kawaii-primary/20',
  ],
  theme: {
    extend: {
      colors: {
        'kawaii-primary': 'rgb(var(--kawaii-primary-rgb) / <alpha-value>)',
        'kawaii-primary-soft': 'var(--kawaii-primary-soft)',
        'kawaii-primary-deep': 'var(--kawaii-primary-deep)',
        'kawaii-primary-glow': 'var(--kawaii-primary-glow)',
        'kawaii-secondary': 'var(--kawaii-secondary)',
        'kawaii-secondary-soft': 'var(--kawaii-secondary-soft)',
        'kawaii-secondary-deep': 'var(--kawaii-secondary-deep)',
        'kawaii-secondary-glow': 'var(--kawaii-secondary-glow)',
        'kawaii-mint': 'var(--kawaii-mint)',
        'kawaii-lavender': 'var(--kawaii-lavender)',
        'kawaii-lemon': 'var(--kawaii-lemon)',
        'kawaii-lemonade': 'var(--kawaii-lemonade)',
        'kawaii-coral': 'var(--kawaii-coral)',
        'kawaii-rose': 'var(--kawaii-rose)',
        'kawaii-peach': 'var(--kawaii-peach)',
        'kawaii-sky': 'var(--kawaii-sky)',
        'kawaii-success': 'rgb(var(--kawaii-success-rgb) / <alpha-value>)',
        'kawaii-warning': 'var(--kawaii-warning)',
        'kawaii-danger': 'rgb(var(--kawaii-danger-rgb) / <alpha-value>)',
        'kawaii-info': 'var(--kawaii-info)',
        'kawaii-ink': 'var(--kawaii-ink)',
        'kawaii-ink-soft': 'var(--kawaii-ink-soft)',
        'kawaii-ink-muted': 'var(--kawaii-ink-muted)',
        'kawaii-paper': 'var(--kawaii-paper)',
        'kawaii-paper-soft': 'var(--kawaii-paper-soft)',
        'kawaii-surface': 'var(--kawaii-surface)',
        'kawaii-surface-elevated': 'var(--kawaii-surface-elevated)',
        'kawaii-panel': 'var(--kawaii-panel)',
        'kawaii-panel-soft': 'var(--kawaii-panel-soft)',
        'kawaii-panel-muted': 'var(--kawaii-panel-muted)',
        'kawaii-line': 'rgb(var(--kawaii-line-rgb) / <alpha-value>)',
        'kawaii-line-soft': 'var(--kawaii-line-soft)',
        'kawaii-accent-soft': 'var(--kawaii-accent-soft)',
        'kawaii-toggle-surface': 'var(--kawaii-toggle-surface)',
        'kawaii-toggle-inset': 'var(--kawaii-toggle-inset)',
        'kawaii-code-surface': 'var(--kawaii-code-surface)',
        'kawaii-code-surface-hover': 'var(--kawaii-code-surface-hover)',
      },
      fontFamily: {
        display: ['Quicksand', 'ZCOOL KuaiLe', 'sans-serif'],
        body: ['Nunito', '-apple-system', 'BlinkMacSystemFont', 'sans-serif'],
        mono: ['SFMono-Regular', 'Menlo', 'Consolas', 'monospace'],
      },
      borderRadius: {
        'kawaii-sm': '12px',
        'kawaii-md': '18px',
        'kawaii-lg': '24px',
        'kawaii-xl': '30px',
      },
      boxShadow: {
        'kawaii-soft': 'var(--shadow-soft)',
        'kawaii-elevated': 'var(--shadow-elevated)',
        'kawaii-glow': 'var(--shadow-glow)',
        'candy-3d': 'var(--candy-3d)',
        'candy-3d-active': 'var(--candy-3d-active)',
      },
      backgroundImage: {
        'gradient-hero': 'var(--gradient-hero)',
        'gradient-card': 'var(--gradient-card)',
        'gradient-button-primary': 'var(--gradient-button-primary)',
        'gradient-button-secondary': 'var(--gradient-button-secondary)',
      },
      transitionTimingFunction: {
        'smooth': 'cubic-bezier(0.4, 0, 0.2, 1)',
        'out-quiet': 'cubic-bezier(0.25, 1, 0.5, 1)',
        'out-gentle': 'cubic-bezier(0.22, 1, 0.36, 1)',
        'playful': 'cubic-bezier(0.34, 1.56, 0.64, 1)',
      },
      animation: {
        'background-float': 'background-float 20s ease-in-out infinite',
        'nebula-float': 'nebula-float 25s ease-in-out infinite',
        'toast-in': 'toast-in 300ms ease',
        'toast-out': 'toast-out 300ms ease forwards',
        'panel-in': 'panel-in 200ms cubic-bezier(0.25, 1, 0.5, 1)',
        'pulse-ring': 'pulse-ring 2s ease-out infinite',
        'modal-in': 'modal-in 300ms cubic-bezier(0.25, 1, 0.5, 1)',
        'fade-in': 'fade-in 200ms ease',

        'shake': 'shake 300ms ease',
      },
      keyframes: {
        'background-float': {
          '0%, 100%': { backgroundPosition: '0% 0%, 0% 0%, 0% 0%, 0% 0%, 0% 0%' },
          '50%': { backgroundPosition: '2% 3%, -2% -3%, 1% -2%, -1% 2%, 0% 0%' },
        },
        'nebula-float': {
          '0%, 100%': { backgroundPosition: '0% 0%, 0% 0%, 0% 0%, 0% 0%, 0% 0%, 0% 0%, 0% 0%, 0% 0%, 0% 0%, 0% 0%' },
          '33%': { backgroundPosition: '3% 2%, -2% 3%, 2% -3%, -3% 2%, 0% 0%, 0% 0%, 0% 0%, 0% 0%, 0% 0%, 0% 0%' },
          '66%': { backgroundPosition: '-2% 3%, 3% -2%, -3% 2%, 2% -3%, 0% 0%, 0% 0%, 0% 0%, 0% 0%, 0% 0%, 0% 0%' },
        },
        'toast-in': {
          from: { opacity: '0', transform: 'translateX(100%)' },
          to: { opacity: '1', transform: 'translateX(0)' },
        },
        'toast-out': {
          from: { opacity: '1', transform: 'translateX(0)' },
          to: { opacity: '0', transform: 'translateX(100%)' },
        },
        'panel-in': {
          from: { opacity: '0', transform: 'translateY(-10px) scale(0.98)' },
          to: { opacity: '1', transform: 'translateY(0) scale(1)' },
        },
        'pulse-ring': {
          '0%': { transform: 'scale(0.95)', opacity: '0.5' },
          '100%': { transform: 'scale(1.15)', opacity: '0' },
        },
        'modal-in': {
          from: { opacity: '0', transform: 'translateY(20px) scale(0.95)' },
          to: { opacity: '1', transform: 'translateY(0) scale(1)' },
        },
        'fade-in': {
          from: { opacity: '0' },
          to: { opacity: '1' },
        },
        'shake': {
          '0%, 100%': { transform: 'translateX(0)' },
          '25%': { transform: 'translateX(-5px)' },
          '75%': { transform: 'translateX(5px)' },
        },
      },
    },
  },
  plugins: [],
}
