"""Initial application schema.

Revision ID: 0001
Revises:
Create Date: 2026-07-14 00:52:48.379216
"""

from __future__ import annotations

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("aggregate_type", sa.String(length=64), nullable=False),
        sa.Column("aggregate_id", sa.String(length=128), nullable=False),
        sa.Column("event_type", sa.String(length=128), nullable=False),
        sa.Column("actor_ref", sa.String(length=255), nullable=False),
        sa.Column("owner_principal_id", sa.Integer(), nullable=True),
        sa.Column("payload_json", sa.Text(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_audit_events_aggregate_type_aggregate_id",
        "audit_events",
        ["aggregate_type", "aggregate_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_audit_events_occurred_at"), "audit_events", ["occurred_at"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_owner_principal_id"),
        "audit_events",
        ["owner_principal_id"],
        unique=False,
    )
    op.create_table(
        "principals",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("slug", sa.String(length=200), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("kind", "slug", name="uq_principals_kind_slug"),
    )
    op.create_index("ix_principals_kind_slug", "principals", ["kind", "slug"], unique=False)
    op.create_table(
        "rate_limit_entries",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("window_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key", "window_start", name="uq_rate_limit_entries_key_window_start"),
    )
    op.create_index(op.f("ix_rate_limit_entries_key"), "rate_limit_entries", ["key"], unique=False)
    op.create_index(
        op.f("ix_rate_limit_entries_window_start"),
        "rate_limit_entries",
        ["window_start"],
        unique=False,
    )
    op.create_table(
        "review_policies",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("version", sa.String(length=64), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("rules_json", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "service_principals",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("principal_id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["principal_id"],
            ["principals.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("principal_id"),
    )
    op.create_index("ix_service_principals_slug", "service_principals", ["slug"], unique=False)
    op.create_table(
        "skills",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("namespace_id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=200), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("default_visibility_profile", sa.String(length=64), nullable=True),
        sa.Column("created_by_principal_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_principal_id"],
            ["principals.id"],
        ),
        sa.ForeignKeyConstraint(
            ["namespace_id"],
            ["principals.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("namespace_id", "slug", name="uq_skills_namespace_id_slug"),
    )
    op.create_index("ix_skills_namespace_id_slug", "skills", ["namespace_id", "slug"], unique=False)
    op.create_table(
        "skill_contents",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("public_id", sa.String(length=64), nullable=False),
        sa.Column("skill_id", sa.Integer(), nullable=False),
        sa.Column("storage_uri", sa.String(length=1000), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("declared_version", sa.String(length=64), nullable=False),
        sa.Column("metadata_json", sa.Text(), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("created_by_principal_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["created_by_principal_id"], ["principals.id"]),
        sa.ForeignKeyConstraint(["skill_id"], ["skills.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_id", name="uq_skill_contents_public_id"),
    )
    op.create_index(
        op.f("ix_skill_contents_created_by_principal_id"),
        "skill_contents",
        ["created_by_principal_id"],
        unique=False,
    )
    op.create_index(
        "ix_skill_contents_skill_id_state", "skill_contents", ["skill_id", "state"], unique=False
    )
    op.create_table(
        "teams",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("principal_id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=200), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["principal_id"],
            ["principals.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("principal_id"),
    )
    op.create_index("ix_teams_slug", "teams", ["slug"], unique=False)
    op.create_table(
        "skill_versions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("skill_id", sa.Integer(), nullable=False),
        sa.Column("content_id", sa.Integer(), nullable=False),
        sa.Column("version", sa.String(length=64), nullable=False),
        sa.Column("content_digest", sa.String(length=255), nullable=False),
        sa.Column("metadata_digest", sa.String(length=255), nullable=False),
        sa.Column("sealed_manifest_json", sa.Text(), nullable=False),
        sa.Column("created_by_principal_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["content_id"],
            ["skill_contents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by_principal_id"],
            ["principals.id"],
        ),
        sa.ForeignKeyConstraint(
            ["skill_id"],
            ["skills.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("content_id"),
        sa.UniqueConstraint("skill_id", "version", name="uq_skill_versions_skill_id_version"),
    )
    op.create_index(
        op.f("ix_skill_versions_created_by_principal_id"),
        "skill_versions",
        ["created_by_principal_id"],
        unique=False,
    )
    op.create_index(
        "ix_skill_versions_skill_id_version",
        "skill_versions",
        ["skill_id", "version"],
        unique=False,
    )
    op.create_table(
        "team_memberships",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["principals.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_team_memberships_team_id"), "team_memberships", ["team_id"], unique=False
    )
    op.create_index(
        op.f("ix_team_memberships_user_id"), "team_memberships", ["user_id"], unique=False
    )
    op.create_index(
        "ix_team_memberships_user_id_team_id",
        "team_memberships",
        ["user_id", "team_id"],
        unique=False,
    )
    op.create_table(
        "releases",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("skill_version_id", sa.Integer(), nullable=False),
        sa.Column("skill_id", sa.Integer(), nullable=True),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("format_version", sa.String(length=32), nullable=False),
        sa.Column("manifest_artifact_id", sa.Integer(), nullable=True),
        sa.Column("bundle_artifact_id", sa.Integer(), nullable=True),
        sa.Column("signature_artifact_id", sa.Integer(), nullable=True),
        sa.Column("provenance_artifact_id", sa.Integer(), nullable=True),
        sa.Column("ready_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("platform_compatibility_json", sa.Text(), nullable=False),
        sa.Column("created_by_principal_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["bundle_artifact_id"], ["artifacts.id"], ondelete="SET NULL", use_alter=True
        ),
        sa.ForeignKeyConstraint(
            ["created_by_principal_id"],
            ["principals.id"],
        ),
        sa.ForeignKeyConstraint(
            ["manifest_artifact_id"], ["artifacts.id"], ondelete="SET NULL", use_alter=True
        ),
        sa.ForeignKeyConstraint(
            ["provenance_artifact_id"], ["artifacts.id"], ondelete="SET NULL", use_alter=True
        ),
        sa.ForeignKeyConstraint(
            ["signature_artifact_id"], ["artifacts.id"], ondelete="SET NULL", use_alter=True
        ),
        sa.ForeignKeyConstraint(
            ["skill_id"],
            ["skills.id"],
        ),
        sa.ForeignKeyConstraint(
            ["skill_version_id"],
            ["skill_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("skill_version_id", name="uq_releases_skill_version_id"),
    )
    op.create_index(
        op.f("ix_releases_created_by_principal_id"),
        "releases",
        ["created_by_principal_id"],
        unique=False,
    )
    op.create_index(op.f("ix_releases_skill_id"), "releases", ["skill_id"], unique=False)
    op.create_index(
        op.f("ix_releases_skill_version_id"), "releases", ["skill_version_id"], unique=False
    )
    op.create_index(
        "ix_releases_skill_version_id_state",
        "releases",
        ["skill_version_id", "state"],
        unique=False,
    )
    op.create_table(
        "artifacts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("release_id", sa.Integer(), nullable=True),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("storage_uri", sa.Text(), nullable=False),
        sa.Column("sha256", sa.String(length=128), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["releases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "exposures",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("release_id", sa.Integer(), nullable=False),
        sa.Column("audience_type", sa.String(length=32), nullable=False),
        sa.Column("listing_mode", sa.String(length=32), nullable=False),
        sa.Column("install_mode", sa.String(length=32), nullable=False),
        sa.Column("review_requirement", sa.String(length=32), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("requested_by_principal_id", sa.Integer(), nullable=True),
        sa.Column("policy_snapshot_json", sa.Text(), nullable=False),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["releases.id"],
        ),
        sa.ForeignKeyConstraint(
            ["requested_by_principal_id"],
            ["principals.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_exposures_release_id_audience_type_state",
        "exposures",
        ["release_id", "audience_type", "state"],
        unique=False,
    )
    op.create_index(
        op.f("ix_exposures_requested_by_principal_id"),
        "exposures",
        ["requested_by_principal_id"],
        unique=False,
    )
    op.create_table(
        "jobs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("kind", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=64), nullable=False),
        sa.Column("payload_json", sa.Text(), nullable=False),
        sa.Column("release_id", sa.Integer(), nullable=True),
        sa.Column("requested_by_user_id", sa.Integer(), nullable=True),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("log", sa.Text(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["releases.id"],
        ),
        sa.ForeignKeyConstraint(
            ["requested_by_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_jobs_kind"), "jobs", ["kind"], unique=False)
    op.create_index(
        "ix_jobs_kind_status_created_at", "jobs", ["kind", "status", "created_at"], unique=False
    )
    op.create_index(op.f("ix_jobs_release_id"), "jobs", ["release_id"], unique=False)
    op.create_index(op.f("ix_jobs_status"), "jobs", ["status"], unique=False)
    op.create_table(
        "access_grants",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("exposure_id", sa.Integer(), nullable=False),
        sa.Column("grant_type", sa.String(length=32), nullable=False),
        sa.Column("subject_ref", sa.String(length=255), nullable=False),
        sa.Column("constraints_json", sa.Text(), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("usage_limit", sa.Integer(), nullable=True),
        sa.Column("usage_count", sa.Integer(), nullable=False),
        sa.Column("created_by_principal_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_principal_id"],
            ["principals.id"],
        ),
        sa.ForeignKeyConstraint(
            ["exposure_id"],
            ["exposures.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_access_grants_created_by_principal_id"),
        "access_grants",
        ["created_by_principal_id"],
        unique=False,
    )
    op.create_index(
        "ix_access_grants_exposure_id_grant_type_state",
        "access_grants",
        ["exposure_id", "grant_type", "state"],
        unique=False,
    )
    op.create_table(
        "review_cases",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("exposure_id", sa.Integer(), nullable=False),
        sa.Column("policy_id", sa.Integer(), nullable=True),
        sa.Column("mode", sa.String(length=32), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("opened_by_principal_id", sa.Integer(), nullable=True),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["exposure_id"],
            ["exposures.id"],
        ),
        sa.ForeignKeyConstraint(
            ["opened_by_principal_id"],
            ["principals.id"],
        ),
        sa.ForeignKeyConstraint(
            ["policy_id"],
            ["review_policies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_review_cases_exposure_id_state", "review_cases", ["exposure_id", "state"], unique=False
    )
    op.create_table(
        "credentials",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("principal_id", sa.Integer(), nullable=True),
        sa.Column("grant_id", sa.Integer(), nullable=True),
        sa.Column("type", sa.String(length=64), nullable=False),
        sa.Column("product_token_name", sa.String(length=200), nullable=False),
        sa.Column("product_token_type", sa.String(length=32), nullable=False),
        sa.Column("product_object_id", sa.Integer(), nullable=True),
        sa.Column("product_scope_type", sa.String(length=32), nullable=False),
        sa.Column("product_scope_id", sa.Integer(), nullable=True),
        sa.Column("issued_for", sa.String(length=200), nullable=False),
        sa.Column("hashed_secret", sa.String(length=255), nullable=False),
        sa.Column("scopes_json", sa.Text(), nullable=False),
        sa.Column("resource_selector_json", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["grant_id"],
            ["access_grants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["principal_id"],
            ["principals.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_credentials_principal_id_type_revoked_at_expires_at",
        "credentials",
        ["principal_id", "type", "revoked_at", "expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_credentials_product_object_id"),
        "credentials",
        ["product_object_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_credentials_product_scope_id"), "credentials", ["product_scope_id"], unique=False
    )
    op.create_table(
        "review_decisions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("review_case_id", sa.Integer(), nullable=False),
        sa.Column("reviewer_principal_id", sa.Integer(), nullable=True),
        sa.Column("decision", sa.String(length=32), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("evidence_json", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["review_case_id"],
            ["review_cases.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_principal_id"],
            ["principals.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("review_decisions")
    op.drop_index(op.f("ix_credentials_product_scope_id"), table_name="credentials")
    op.drop_index(op.f("ix_credentials_product_object_id"), table_name="credentials")
    op.drop_index(
        "ix_credentials_principal_id_type_revoked_at_expires_at", table_name="credentials"
    )
    op.drop_table("credentials")
    op.drop_index("ix_review_cases_exposure_id_state", table_name="review_cases")
    op.drop_table("review_cases")
    op.drop_index("ix_access_grants_exposure_id_grant_type_state", table_name="access_grants")
    op.drop_index(op.f("ix_access_grants_created_by_principal_id"), table_name="access_grants")
    op.drop_table("access_grants")
    op.drop_index(op.f("ix_jobs_status"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_release_id"), table_name="jobs")
    op.drop_index("ix_jobs_kind_status_created_at", table_name="jobs")
    op.drop_index(op.f("ix_jobs_kind"), table_name="jobs")
    op.drop_table("jobs")
    op.drop_index(op.f("ix_exposures_requested_by_principal_id"), table_name="exposures")
    op.drop_index("ix_exposures_release_id_audience_type_state", table_name="exposures")
    op.drop_table("exposures")
    op.drop_table("artifacts")
    op.drop_index("ix_releases_skill_version_id_state", table_name="releases")
    op.drop_index(op.f("ix_releases_skill_version_id"), table_name="releases")
    op.drop_index(op.f("ix_releases_skill_id"), table_name="releases")
    op.drop_index(op.f("ix_releases_created_by_principal_id"), table_name="releases")
    op.drop_table("releases")
    op.drop_index("ix_team_memberships_user_id_team_id", table_name="team_memberships")
    op.drop_index(op.f("ix_team_memberships_user_id"), table_name="team_memberships")
    op.drop_index(op.f("ix_team_memberships_team_id"), table_name="team_memberships")
    op.drop_table("team_memberships")
    op.drop_index("ix_skill_versions_skill_id_version", table_name="skill_versions")
    op.drop_index(op.f("ix_skill_versions_created_by_principal_id"), table_name="skill_versions")
    op.drop_table("skill_versions")
    op.drop_index("ix_skill_contents_skill_id_state", table_name="skill_contents")
    op.drop_index(op.f("ix_skill_contents_created_by_principal_id"), table_name="skill_contents")
    op.drop_table("skill_contents")
    op.drop_index("ix_teams_slug", table_name="teams")
    op.drop_table("teams")
    op.drop_index("ix_skills_namespace_id_slug", table_name="skills")
    op.drop_table("skills")
    op.drop_index("ix_service_principals_slug", table_name="service_principals")
    op.drop_table("service_principals")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_table("users")
    op.drop_table("review_policies")
    op.drop_index(op.f("ix_rate_limit_entries_window_start"), table_name="rate_limit_entries")
    op.drop_index(op.f("ix_rate_limit_entries_key"), table_name="rate_limit_entries")
    op.drop_table("rate_limit_entries")
    op.drop_index("ix_principals_kind_slug", table_name="principals")
    op.drop_table("principals")
    op.drop_index(op.f("ix_audit_events_owner_principal_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_occurred_at"), table_name="audit_events")
    op.drop_index("ix_audit_events_aggregate_type_aggregate_id", table_name="audit_events")
    op.drop_table("audit_events")
    # ### end Alembic commands ###
